service: migrates-cloud-provider-function
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  randomCommit:
    handler: handler.randomCommit
    events:
      - http:
          path: commit
          method: get
          cors: true
